### PR TITLE
Differentiate offchain/onchain (Aiken) addresses

### PR DESCRIPTION
**Pull request by mpizenberg**
This PR is to address #19

### CODE REVIEW

**Comment by mpizenberg** [comment]
I think I missed the fact that there are also stake addresses :( https://github.com/cardano-foundation/CIPs/blob/master/CIP-0019/README.md#stake-addresses

Hum maybe it does not make sense to try to use `OnChainAddress` within `Address`. Since their decoders/encoders are different anyway. Maybe we should instead have a dedicated `Aiken` namespace with types, encoders, decoders specifically for compatibility with Aiken. That could also be better to eventually have a compatibility with other on-chain representations like plu-ts, opshin or others. Each their own namespace. There might be a little code duplication but it may be better overall, more flexible than trying to reuse what is basically Aiken choice of representation inside our `Address` type.

**Comment by keyan-m** [comment]
> Maybe we should instead have a dedicated `Aiken` namespace with types, encoders, decoders specifically for compatibility with Aiken.

Doesn't sound like a great idea... Is this a common practice? However, specifically for the `Address` datatype, this doesn't _seem_ to be needed. Would it be too annoying to carry the network ID everywhere?
```elm
type alias Address =
    { networkId : NetworkId
    , paymentCredential : Credential
    , stakeCredential : Maybe StakeCredential
    }
```

(Hopefully I haven't missed any prior conversations 😅)

**Comment by mpizenberg** [comment]
There isn't much discussion on this except the initial issue #19 .

My main motivation is to have a very good interface with Aiken. And Aiken has their Address type defined like this: 
```rust
// Aiken
Address {
  payment_credential: PaymentCredential,
  stake_credential: Option<StakeCredential>,
}
```
I know from my side project that sending addresses in datums / redeemers will be needed. That's why I want to have a type + encoders ready for that.

Now I think it's probably not how other libraries like opshin, plu-ts, plutus-tx encode their addresses for onchain usage. So that's the reason it's probably not a good idea to have that structure forced into the generic `Address` type supposed to be able to handle full addresses (network id, stake addresses, etc.)

However I'll still want to have types ready-to be used for some of the common types in aiken for easier interop. I'm just realizing that it should probably be scoped in a different namespace, independent of the normal address module. That's why I'm talking about another namespace.

But maybe it should not even be in this library. So instead of having a module `Cardano.Aiken.Address` in this elm-cardano package, it should live in another package, like `elm-cardano-aiken` or similar. I don't know XD.

**Comment by keyan-m** [comment]
Isn't network ID a piece of information that's only applicable within an off-chain context?

**Comment by mpizenberg** [comment]
Ok let's actually close this. It make no sense, at the current time to worry about Aiken `Address`. Let's just make the normal `Address` actually able to represent all addresses offchain.

**Pull request closed without merging**
