### PR TITLE
[WIP] Implement CIP-0067

### PR DESCRIPTION
**Pull request by keyan-m**
Implementation of CIP-0067 which is a prerequisite for CIP-0068.

### CODE REVIEW

**Comment by mpizenberg** [comment]
Thanks for this @keyan-m , it's a very nice addition to elm-cardano!

I've done the following few changes:
- extracted Crc8 into its own module
- added tests for Crc8
- added tests for Cip67

Let me know what you think and if I've done changes you find unclear.

**Comment by keyan-m** [comment]
I think you've made nice improvements, thank you :)

**Comment by mpizenberg** [comment]
One last thing. Can we get rid of `rtfeldman/elm-hex`? I haven't checked which functions are called from it but it would be nice if we don't need another dependency.

**Comment by keyan-m** [comment]
> One last thing. Can we get rid of `rtfeldman/elm-hex`? I haven't checked which functions are called from it but it would be nice if we don't need another dependency.

It's used for `toDecimal` and `fromDecimal` in `Bytes.Comparable`. These two were needed for implementing the CRC-8 digest, which requires bitwise operations (it obviously can be found without them, but I believe this is the most optimized implementation). The bitwise operations available in Elm's core library work with `Int` values, hence the conversions of `Bytes` to decimals.

I myself don't love the extra dependency, but it's a very minimal package, and I haven't been able to find another way around it... Perhaps developing a complete CRC package for Elm? 😅

**Comment by mpizenberg** [comment]
Alright, I removed the dependency by leveraging elm/bytes encoders and decoders directly since they have a few stuff dealing with U8 and U16 already. All tests are passing so it should be good.

**Comment by mpizenberg** [comment]
Thanks @keyan-m !
There is still the decoder which is a TODO, but we can deal with that later when we actually start decoding stuff.

**Comment by keyan-m** [comment]
OK nice, I should've looked at `Bytes` a bit more carefully!

**Pull request merged**
